### ISSUE TITLE
Added text & link in Hannah's page

### ISSUE THREAD

**Issue by DrMattG** [softloud/matchametaresearch#4]
I added some text and the link - sorry if its nonsense - it has been a long day! Change whatever you need to - I was not sure about embedding the link (do we do something different - I assume yes but I am clueless).

**Comment by softloud** [comment]
Embedded! 

Just in case you're interested, embedding is easier that it appears. Clicking on the share button gives an option to get the code to embed the video. Copy the code block and drop it wholesale into the markdown doc :) And we look like web wizards.  

![image](https://user-images.githubusercontent.com/13408706/82505417-078bbf80-9b41-11ea-803f-811a75d766ee.png)

**Comment by DrMattG** [comment]
Wow! That is far too easy!

**Comment by softloud** [comment]
Shhh don't tell anyone and we'll look like web ninjas.
