### ISSUE TITLE
Added Gav 

### ISSUE THREAD

**Issue by DrMattG** [softloud/matchametaresearch#5]
I've added Gav but I think you need to do something before it renders to the webpage….(I am not even sure if "render" is the right word but it sounds good). I have also changed googlesheets to googlesheets4 (https://googlesheets4.tidyverse.org/) because googlesheets will be archived soon (see https://github.com/jennybc/googlesheets).

**Comment by softloud** [comment]
btw your rmarkdown code was fine for the image, just needed to change the
capitalisation of one letter in the name of the .jpg.
